version: '3.9'

services:
  bot:
    build: ./
    depends_on:
      - api
    restart: on-failure

  api:
    build:
      dockerfile: api/Dockerfile
    env_file:
      - .env_api
    ports:
      - "8081:8081"
